// Icon set — Solar Icons, exported under the names the app previously imported
// from lucide-react. This is the single swap point for the icon library; call
// sites keep using the same names (e.g. `Search`, `Home`). The global weight is
// set once via SolarProvider (see main.jsx). Solar components accept `size`,
// `color`, and `className`; a leftover `strokeWidth` from old call sites is an
// ignored SVG attribute, so no call site needed changing.
export {
    ArrowLeft,
    ArrowRight,
    Hashtag as AtSign,
    ChartSquare as BarChart3,
    Bell,
    Calendar as CalendarClock,
    Calendar as CalendarDays,
    CheckCircle as Check,
    CheckCircle as CircleCheck,
    AltArrowDown as ChevronDown,
    TransferVertical as ChevronsUpDown,
    UserRounded as Contact,
    SquareArrowRightUp as ExternalLink,
    FolderOpen,
    QuestionCircle as HelpCircle,
    Home,
    Widget as LayoutDashboard,
    Widget2 as LayoutGrid,
    List,
    Refresh as LoaderCircle,
    Refresh as RefreshCw,
    Lock,
    Logout as LogOut,
    Speaker as Megaphone,
    Sidebar as PanelLeft,
    SidebarMinimalistic as PanelLeftClose,
    PlugCircle as Plug,
    AddSquare as Plus,
    Magnifer as Search,
    Plain as Send,
    Settings,
    SkipNext as SkipForward,
    StarShine as Sparkles,
    Target,
    Telescope,
    TrashBinMinimalistic as Trash2,
    GraphUp as TrendingUp,
    DangerTriangle as TriangleAlert,
    Text as Type,
    UndoLeftRound as Undo2,
    UserPlusRounded as UserSearch,
    UsersGroupRounded as Users,
    CloseCircle as X,
} from '@solar-icons/react';
